### ISSUE TITLE
thrust/device_vector.h file is missing

### ISSUE THREAD

**Issue by blasheroy** [ShuangLI59/person_search#10]
May I know the "thrust/device_vector.h" file located at which directory? I search through the whole project file but cannot find the "thrust/device_vector.h" file.
The "person_search/caffe-fast-rcnn/src/caffe/layers/cudnn_softmax_layer.cpp" file fail to run #include "thrust/device_vector.h" when I try to make pycaffe
 
![screenshot from 2016-10-26 11 13 31](https://cloud.githubusercontent.com/assets/18228712/19712202/608a66bc-9b6e-11e6-95f9-a73d6638137d.png)

**Comment by Cysu** [comment]
This is actually a cuda header. Could you please check if your cuda home (typically `/usr/local/cuda`) contains `include/thrust/device_vector.h`?

**Comment by blasheroy** [comment]
Thanks for your advise. Problem solved after I create a symbolic link at person_search/caffe-fast-rcnn/include which link to /usr/local/cuda-7.5/targets/x86_64-linux/include/thrust
