### ISSUE TITLE
ValueError: Array contains NaN or infinity

### ISSUE THREAD

**Issue by blasheroy** [ShuangLI59/person_search#11]
Hi, I know this issue had been discussed before but the problem still exists after I do pip install -U scikit-learn
My scikit-learn version is 0.18
![e42545b6-9c34-11e6-8ccd-0d3b4d382ab2](https://cloud.githubusercontent.com/assets/18228712/19755335/bb276fe6-9c47-11e6-82c2-a0abc9ac95ec.png)

**Comment by Cysu** [comment]
@blasheroy Could you please check the output of the following commands?

    which python
    which pip
    pip freeze | grep scikit-learn

According to the [source code](https://github.com/scikit-learn/scikit-learn/tree/master/sklearn/metrics), there is no metrics.py indeed in version 0.18. Maybe there is a mismatch between your python and pip.

**Comment by blasheroy** [comment]
![screenshot from 2016-10-27 13 58 42](https://cloud.githubusercontent.com/assets/18228712/19756301/2d93ceac-9c4e-11e6-9452-eadcfe3f8684.png)

**Comment by Cysu** [comment]
It seems that `pip` is under `/usr/local/bin`, while `python` is under `/usr/bin`. So it uses `/usr/lib/python2.7` but not `/usr/local/lib/python2.7`.

Please check if there is another python in `/usr/local/bin`. If so, you can just add `export PATH=/usr/local/bin:$PATH` at the end of `~/.bashrc` and restart the terminal.

**Comment by blasheroy** [comment]
Unfortunately, there is no python in /usr/local/bin
Please advise me what should I do next.
Thanks.
![screenshot from 2016-10-27 15 09 13](https://cloud.githubusercontent.com/assets/18228712/19757874/fb46d296-9c57-11e6-8708-082fc6a4b289.png)

**Comment by Cysu** [comment]
There might be two solutions:

1. Uninstall the /usr/local/bin/pip, and use the system python and pip in /usr/bin
2. Install [anaconda](https://www.continuum.io/downloads) locally under your account, and use the anaconda's python.

**Comment by blasheroy** [comment]
I tried run your code on another desktop that does not has issue with the pip and python and it's works. 
Thank you very much!
