### ISSUE TITLE
demo.py  error

### ISSUE THREAD

**Issue by bigyouzi** [ShuangLI59/person_search#116]

**Comment by bigyouzi** [comment]
when demo.py ,I have the error:
$python tools/demo.py --gpu 0
Traceback (most recent call last):
  File "tools/demo.py", line 114, in <module>
    main(args)
  File "tools/demo.py", line 30, in main
    caffe.mpi_init()
AttributeError: 'module' object has no attribute 'mpi_init'

My version of openmpi is 1.10.5,the version of cuda and cudnn are cuda7.5 and cudnn5.1
How to solve the problem?

**Comment by SiyuanHuang95** [comment]
Have you solved this problem? And how?

Thx in advance!
