### ISSUE TITLE
faster_rcnn_test.pt is not found

### ISSUE THREAD

**Issue by crogerjack** [ShuangLI59/person_search#12]
Hi, I try to run the demo.py but it shows the faster_rcnn_test.pt is not found. May I know where can I get the file? The pascal_voc directory does not exist in person_search/models/
![screenshot from 2016-11-16 16 12 40](https://cloud.githubusercontent.com/assets/16471997/20339502/a858478e-ac17-11e6-82aa-f22293295009.png)

**Comment by Cysu** [comment]
The demo is currently broken. I will replace it by a web-based visualization tool later when I have some time. Sorry for the inconvenience temporarily.

**Comment by Cysu** [comment]
We provide a web-based visualization tool now.
