### ISSUE TITLE
higher mAP&top-1 with default setting

### ISSUE THREAD

**Issue by huanhsu** [ShuangLI59/person_search#13]
Hi @ShuangLI59 
I download pretrained model& trained model and run with default code.
However, it shows mAP= 69.69%, top-1= 72.97%.

Any idea?

**Comment by Cysu** [comment]
There was a bug in the evaluation code for our method. We fixed it and the result of our model is actually much better than our paper reported. Will update a new version of paper on arXiv recently.

**Comment by huanhsu** [comment]
Thanks
