### ISSUE TITLE
bounding boxes wander around in a search in video

### ISSUE THREAD

**Issue by mostafachatillon** [ShuangLI59/person_search#14]
I am applying this project to search Angela Merkel in a crowd, but the bounding boxes keep wandering over various persons, instead of recognizing her. My threshold is 1293. If I lower the detection threshold one unit further, it does not recognize anything.

resulting video here: https://drive.google.com/file/d/0B86WKpvkt66Bc3o0d3F4eXBPZFU/view?usp=sharing 

Input image here: 
![merkel2](https://cloud.githubusercontent.com/assets/8183572/20947520/3c94b35a-bc18-11e6-8cc9-23ba4491b0cd.png)

input video here: https://drive.google.com/file/d/0B86WKpvkt66BM3FrZFg5eExtOEk/view?usp=sharing

code that I modified is here: 
create_video.py: https://drive.google.com/file/d/0B86WKpvkt66BTWtVYUdmamRkcDg/view?usp=sharing

test_gallery_batch.py
https://drive.google.com/file/d/0B86WKpvkt66BTWtVYUdmamRkcDg/view?usp=sharing

**Comment by Cysu** [comment]
The result video is quite weird. I am on travel now and will definitely look into the scripts later this week when I come back. Thank you for your patience on this.

**Comment by mostafachatillon** [comment]
It was only a small typo in my code, sorry for the false alarm. Everything works well, good job!

**Comment by andongchen** [comment]
@Cysu Could share me you search in video,you gave test_gallery_batch.py link as the same of create_video.py 
Thanks

**Comment by Cysu** [comment]
@andongchen I guess you want to mention @mostafachatillon for the request?

**Comment by mostafachatillon** [comment]
@andongchen I shared the videos with you, tell me if you have more problems.

**Comment by andongchen** [comment]
@mostafachatillon 
I want your test_gallery_batch.py code,and one problem in your creat_video code:filelist = [ f for f in os.listdir("static/images") ], where is the static/images?

**Comment by mostafachatillon** [comment]
@andongchen I did not find it, but it is very similar to the file in the repository. the 'static/images' folder is where your input images are stored.

**Comment by njustzjw** [comment]
@mostafachatillon 
Hello,
I have a question to ask you, how do you train your own data set, or how do you add labels to your data?
I am a freshman on Deep Learning.When I use the ShuangLI59/person_search project,I want to train my own dataset, but I don't know what I should do with my data.
How do I translate my data into data types that can be identified by the project?
Many thanks for your help
