### ISSUE TITLE
Question: what about difference in clothes?

### ISSUE THREAD

**Issue by mostafachatillon** [ShuangLI59/person_search#15]
I don't have an issue, but a question: in my experiments, the search does not work so well when the query and the gallery persons have different clothes. 

In the training sets, including your new dataset, the same person always has the same clothes. 

Why not detecting the same person with different clothes? That is important in many practical applications.

**Comment by Cysu** [comment]
In my opinion, it would rely mostly on face verification to search the person when clothes change. Our problem aims at searching a person across different camera views in a short time period, especially when the face is not clearly visible. Your suggestion is important but a different problem setting.

**Comment by mostafachatillon** [comment]
I meant this kind of setting: 
![merkelnew3](https://cloud.githubusercontent.com/assets/8183572/21076222/cdad511c-bf2e-11e6-8a2b-4d09023057e2.png)

The face is not clearly visible, but it remains partially visible, The hair are visible, and by also looking at the body shape, I think a human could recognize Angela Merkel (at least, in a crowd with various people).

 On the other hand, your model can't (if she wears different clothes), and I don't know whether any model can. 

But it is a more realistic setting: people do not look at cameras, but they do not completely oppose it either. They change their clothes, but their body shape remains relatively constant.

**Comment by Cysu** [comment]
Thanks very much for the explanation. In my opinion, there could be lots of confusing samples in real world data for your problem setting. Maybe it can be done for some specific celebrities. I would recommend Ning Zhang's [work](https://arxiv.org/abs/1501.05703) for this purpose.
