### ISSUE TITLE
undefined symbol: sqlite3_column_table_name

### ISSUE THREAD

**Issue by hizhangp** [ShuangLI59/person_search#2]
When training the model, I met the problem below:
```
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /usr/lib/libgdal.so.1: undefined symbol: sqlite3_column_table_name
```
But py-faster-rcnn can run properly in my device.

**Comment by Cysu** [comment]
Sorry but I can hardly figure out why this happened. Could you please try to recompile the caffe-fast-rcnn,  `cd caffe-fast-rcnn/python`, and then `python -c "import python"`?

**Comment by hizhangp** [comment]
@Cysu Thanks, I use the python2 in Ubuntu instead of Anaconda2 and the problem solved, maybe there is a conflict in the package of Anaconda .
