### ISSUE TITLE
Where I can see the code of OIM Loss ?

### ISSUE THREAD

**Issue by xueyuxiaolang** [ShuangLI59/person_search#20]
I've successfully run the code and want to know more about code. where I can see OIM loss function?thanks

**Comment by Cysu** [comment]
It actually combines multiple layers. Please check [this part](https://github.com/ShuangLI59/person_search/blob/master/models/psdb/resnet50/train.prototxt#L3077-L3159) of the prototxt.

**Comment by xueyuxiaolang** [comment]
Thanks for your help ! Now I have another question: how to visualize, I  copy the results.json to vis/ and run python2 -m SimpleHTTPServer. Then open a browser and go to http://localhost:8000/vis. But I see:
Error response

Error code 404.

Message: File not found.

Error code explanation: 404 = Nothing matches the given URI.

How can I do  the Visualization?

**Comment by Cysu** [comment]
In which directory do you run the `python2 -m SimpleHTTPServer`? If already under `vis/`, then you need to visit http://localhost:8000.

**Comment by xueyuxiaolang** [comment]
Thanks, Now When I under vis/, then you need to visit http://localhost:8000. I can see the index,but no picture.I'm sure that I copy the result.json to vis/

**Comment by Cysu** [comment]
It's a little bit weird. Do you make sure your data is under `data/psdb/dataset/Image/SSM/`? Could you please check if there are any errors in the webpage by using the "Inspect" (审查元素) in Chrome?

**Comment by xueyuxiaolang** [comment]
Thank you very much.Now I can see the visualization.
