### ISSUE TITLE
Have troble making Caffe in the project

### ISSUE THREAD

**Issue by milanyummy** [ShuangLI59/person_search#23]
Thank you for your work! I want to try this demo on the server，but I cannot build the caffe.
I encountered an error when the step  "make -j8 && make install"is performed, and the error information is 
"../lib/libcaffe.so: undefined reference to `google::protobuf::io::CodedInputStream::ReadTagFallback(unsigned int)'
../lib/libcaffe.so: undefined reference to `google::protobuf::internal::MergeFromFail(char const*, int)'
../lib/libcaffe.so: undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::InternalExtend(int)'
../lib/libcaffe.so: undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/cpp_classification/classification] Error 1
make[1]: *** [examples/CMakeFiles/classification.dir/all] Error 2
make: *** [all] Error 2"
Hope you can provide some help. Thank you!

**Comment by Cysu** [comment]
Could you please check the output of the following commands?
```bash
ldd caffe/build/lib/libcaffe.so | grep proto
which protoc
protoc --version
```

**Comment by milanyummy** [comment]
Good afternoon. Here are the response of these commands:
gym@amax:~/Documents/person_search_v2$ ldd caffe/build/lib/libcaffe.so |grep proto
	libprotobuf.so.8 => /usr/lib/x86_64-linux-gnu/libprotobuf.so.8 (0x00007f88e1bbe000)
gym@amax:~/Documents/person_search_v2$ which protoc
/home/gym/anaconda2/bin/protoc
gym@amax:~/Documents/person_search_v2$ protoc --version
libprotoc 3.0.0

**Comment by Cysu** [comment]
It seems that the system's protobuf conflicts with anaconda's. Could you please uninstall anaconda's protobuf by
```bash
conda uninstall protobuf
pip install protobuf
```
After this, we should expect ``which protoc`` to point to some system binary like ``/usr/bin/protoc``.

And then remove the build directory and try to compile the caffe again.

**Comment by milanyummy** [comment]
I have uninstallde anaconda's protobuf and used the pip to install the protobuf.
But now which protoc still points to /home/gym/anaconda2/bin/protoc

**Comment by milanyummy** [comment]
I have uninstallde anaconda's protobuf and used the pip to install the protobuf.
But now  which protoc  still points to  /home/gym/anaconda2/bin/protoc

**Comment by milanyummy** [comment]
算了，还是用中文好了。
之前我已经运行
conda uninstall protobuf
pip install protobuf
但是还是没有变化，which protoc 依然指向 /home/gym/anaconda2/bin/protoc

**Comment by Cysu** [comment]
Do you have multiple versions of anaconda? Could you please check the output of ``which conda``?

How about running only ``conda uninstall protobuf``? I think this command should delete ``/home/gym/anaconda2/bin/protoc``.

**Comment by milanyummy** [comment]
Hello！
The output of which conda is  /home/gym/anaconda2/bin/conda.
And I ran conda uninstall protobuf but /home/gym/anaconda2/bin/protoc is still exist.

**Comment by milanyummy** [comment]
Hello！
The output of which conda is /home/gym/anaconda2/bin/conda.
And I ran conda uninstall protobuf but /home/gym/anaconda2/bin/protoc still exists.

**Comment by Cysu** [comment]
That's weird. I have just tried with my computer and it worked. Could you please try to update anaconda by ``conda update --all``?

**Comment by Cysu** [comment]
@milanyummy Any luck on this issue?
