### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by joyyang1215** [ShuangLI59/person_search#31]
When I run experiments/scripts/eval_test.sh resnet50 50000 resnet50 to evaluate the pre-trained model, I got the following error. It looks like something based on MATLAB.
`IOError: [Errno 2] No such file or directory: '/path/to/person_search/data/psdb/dataset/annotation/pool.mat'`
Could you help me with?

**Comment by Cysu** [comment]
Did you run the script
```bash
experiments/scripts/prepare_data.sh /path/to/the/downloaded/dataset.zip
```
It should unzip the raw data to `data/psdb/dataset`, which should contain two directories, `annotation/` and `Image/`.

**Comment by joyyang1215** [comment]
Oh, I see. I just load the trained model, so that I miss those files you mention.

**Comment by Cysu** [comment]
Sure. That's no problem.

**Comment by joyyang1215** [comment]
Could you please send it to me?
Or how can I get the download link?

**Comment by Cysu** [comment]
@joyyang1215 I have received your email and written back with the download link. Please check. Thanks.

**Comment by leemtt** [comment]
@joyyang1215  hello ，I meet the same error as you。It's frustrating for me 。How do you solve this problem? Can you send me a link of the dataset? thank you so much.
