### ISSUE TITLE
How can I run the code of psdb.py

### ISSUE THREAD

**Issue by 22wei22** [ShuangLI59/person_search#32]
How can I run the code of psdb.py  I want to get CMC and mAP curve

**Comment by Cysu** [comment]
You may refer to this [function call](https://github.com/ShuangLI59/person_search/blob/master/tools/eval_test.py#L106-L109) as an example. Basically you just need to send in detected gallery bounding boxes, their corresponding features, as well as the probe features, as explained [here](https://github.com/ShuangLI59/person_search/blob/master/lib/datasets/psdb.py#L201-L212).

**Comment by 22wei22** [comment]
I am a undergraduate student,I really can not get the CMC and mAP curve,Could you tell me how to do it specifically such as how to run demo?Thank you very much

**Comment by Cysu** [comment]
Do you have problems with running the evaluation command
```bash
experiments/scripts/eval_test.sh resnet50 50000 resnet50
```
or do you want to use the evaluation code to test your own method?

**Comment by 22wei22** [comment]
experiments/scripts/eval_test.sh resnet50 50000 resnet50 This is ok.Now I just want to get your CMC and mAP curve .it is not mine

**Comment by Cysu** [comment]
Ok, I got it. To get the full CMC curve, you may need to add `return accs` at the end of the [evaluation function](https://github.com/ShuangLI59/person_search/blob/master/lib/datasets/psdb.py#L328-L338). This is the CMC values starting from top-1. You can then fetch and print the return value at [here](https://github.com/ShuangLI59/person_search/blob/master/tools/eval_test.py#L106-L109)
```python
cmc = imdb.evaluate_search(...)
print cmc
```

I'm afraid you cannot get the mAP curve, as mAP is a scalar itself.

**Comment by njustzjw** [comment]
Hey,could you tell me how to  get the dataset the author provided in  README?Thank you very much!
