### ISSUE TITLE
Cannot find Normalize type for feat layer

### ISSUE THREAD

**Issue by l2cheng** [ShuangLI59/person_search#35]
Hi,

I am trying to run the demo.py using CPU only. I encountered the problem of undefined Normalize type which is defined in 'feat' layer. And I checked the caffe folder, and there is no Normalize layer code there. 

Do you have any clue to solve this problem? Thank you very much for your help.

**Comment by Cysu** [comment]
Did you clone the repo recursively with
```bash
git clone --recursive https://github.com/ShuangLI59/person_search.git
```
We do have normalization layer [here](https://github.com/Cysu/caffe/blob/aed38841ae4282d90575186b87c3287620913722/src/caffe/layers/normalize_layer.cpp)

**Comment by l2cheng** [comment]
Thanks. I run the demo successfully
