### ISSUE TITLE
how to train model?

### ISSUE THREAD

**Issue by Phoebe-star** [ShuangLI59/person_search#36]
Can you tell me how to train the model?

**Comment by Cysu** [comment]
Please follow the steps in [README](https://github.com/ShuangLI59/person_search#experiments).

**Comment by Phoebe-star** [comment]
can it train own data?  thanks

**Comment by Cysu** [comment]
Yes, you may create a new class for your own dataset, just as the [psdb.py](https://github.com/ShuangLI59/person_search/blob/master/lib/datasets/psdb.py).

**Comment by Phoebe-star** [comment]
sorry I have not know idea , what is the data format, is it like VOC dataset

**Comment by njustzjw** [comment]
Hey,could you tell me how to  get the dataset the author provided in  README?Thank you very much!

**Comment by Cysu** [comment]
The data is stored in an [roidb](https://github.com/ShuangLI59/person_search/blob/master/lib/datasets/psdb.py#L124-L129) that contains ground truth bbox locations and their person ids for each image.
