### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by tankienleong** [ShuangLI59/person_search#44]
From the experiments/cfgs/resnet50.yml, may I know what is the difference between IMS_PER_BATCH and BATCH_SIZE?

**Comment by Cysu** [comment]
IMS_PER_BATCH is how many whole scene images inside each mini-batch. It is fixed as 1 in our project.

BATCH_SIZE is how many pedestrian proposals, or region of interests (RoIs) equivalently, in each mini-batch.

**Comment by tankienleong** [comment]
I see. 
Does the BATCH_SIZE related to the number of labeled identities inside the Lookup Table?

**Comment by Cysu** [comment]
No. The total number of labeled identities is 5532. BATCH_SIZE is how many bounding boxes proposed by the pedestrian proposal network.

**Comment by tankienleong** [comment]
Did you mean the number of labeled identities inside the Lookup Table always fixed at 5532 throughout the training process? 
I feel confused, what is the difference between RPN_BATCHSIZE and BATCH_SIZE?

**Comment by Cysu** [comment]
@tankienleong Yes, the size of the Lookup Table is fixed at 5532 during training.

Our framework is based on Faster-RCNN, which can be thought of as a cascaded detector. The first stage regresses an anchor to a proposal, the second stage further refines and classifies the proposal. `RPN_BATCHSIZE` is used for the first stage while `BATCH_SIZE` is for the second stage.

**Comment by tankienleong** [comment]
Hi @Cysu May I know which part of the code define the value of temperature T for both of the equation 1 and equation 2 in your paper "Joint Detection and Identification Feature Learning for Person Search"? I had read the code in softmax_loss_layer.cpp & softmax_loss_layer.cu but fail to figured out what is the value of T.

**Comment by Cysu** [comment]
@tankienleong It's actually implemented by using the Power layer in prototxt, see [here](https://github.com/ShuangLI59/person_search/blob/master/models/psdb/resnet50/train.prototxt#L3097-L3105).

**Comment by twmht** [comment]
@Cysu 

in the paper, the  value of T is set to 0.1, why you set T to 10 in the prototxt?

**Comment by Cysu** [comment]
@twmht, score / 10 = score * 0.1, we just use reciprocal of T.

**Comment by twmht** [comment]
@Cysu 

I have looked at `labeled_matching_layer`, this only implements cosine similarity.

and the succeeding power layer multiples the similarity score by 10, not divided by 10.

see caffe (http://caffe.berkeleyvision.org/tutorial/layers/power.html)

**Comment by Cysu** [comment]
@twmht, my bad, I mean score / 0.1 = score * 10. The temperature T is 0.1, we use its reciprocal for simpler implementation.
