### ISSUE TITLE
What are the features of pedestrian proposals calculated through the net?

### ISSUE THREAD

**Issue by njustzjw** [ShuangLI59/person_search#45]
What are the features of pedestrian proposals calculated through the net? When I test, some people have different colors of clothes, they will be mistaken for target, for example, I want to identify those who wear white clothes, but the result is the one wears black clothes.

**Comment by Cysu** [comment]
It's hard for me to answer it. I think the features may capture clothes color / style, human body shape, and even facial information if available. But it's not easy to understand why deep learning model fails on some hard cases.

By the way, did you use the code tools/demo.py for your own test?

**Comment by njustzjw** [comment]
Yes，I found grey clothes and black clothes or white clothes, their similarity value are about the same, but I think the gap should be distinguished by deep features. Maybe we can optimize the structure of the net , such as increasing conv layers or doing some features fusion between the bottom layer and top layer.




发自网易邮箱大师
On 08/07/2017 10:25, Tong Xiao wrote:

It's hard for me to answer it. I think the features may capture clothes color / style, human body shape, and even facial information if available. But it's not easy to understand why deep learning model fails on some hard cases.

By the way, did you use the code tools/demo.py for your own test?
