### ISSUE TITLE
Error when running demo

### ISSUE THREAD

**Issue by ChaoqunHong** [ShuangLI59/person_search#47]
When I try
python2 tools/demo.py --gpu 0
to run the demo, I get the following error:
person_search/caffe/build2/lib/libcaffe.so: undefined symbol: ompi_mpi_double

**Comment by Cysu** [comment]
@ChaoqunHong Could you please show the output of the following commands?

```bash
which mpirun
mpirun --version
ldd person_search/caffe/build2/bin/caffe | grep mpi
```
