### ISSUE TITLE
What is the number of training images inside train.mat file?

### ISSUE THREAD

**Issue by tankienleong** [ShuangLI59/person_search#48]
Hi, I had wrote a matlab program to convert your train.mat file into xml format for other cnn model training. The output of my matlab program shows 9616 training images but your journal mentioned there are 11206 training images. Can you provide the list of training images (something like pool.mat)? so that I can debug my matlab program more easily.

**Comment by tankienleong** [comment]
I tried my matlab program with TestG50.mat and TestG1000.mat and the output shows 6978 test images respectively which is same as the number of test images mentioned inside your journal.

**Comment by Cysu** [comment]
@tankienleong Sorry for the delayed response.

There are in total 18184 images and 6978 of them for test. The remaining 18184 - 6978 = 11206 images are all used for training. Please refer to this part of [code](https://github.com/ShuangLI59/person_search/blob/master/lib/datasets/psdb.py#L408-L412).

The Train.mat contains the labeled identities. There are also some unlabeled identities in other images.
