### ISSUE TITLE
Demo.py failing

### ISSUE THREAD

**Issue by kalravibhor** [ShuangLI59/person_search#54]
Hi, 

Even though I know this is not an Open MPI forum, I still want to try and get some help since I have tried most if not all of the suggestions out there but nothing seems to have worked. I managed to successfully build and install OpenMPI on Ubuntu 16.04 and caffe. However when I try and run the demo, I get the following error : 

``mca_base_component_repository_open: unable to open mca_patcher_overwrite: /usr/local/mpi/lib/openmpi/mca_patcher_overwrite.so: undefined symbol: mca_patcher_base_patch_t_class
mca_base_component_repository_open: unable to open mca_shmem_sysv: /usr/local/mpi/lib/openmpi/mca_shmem_sysv.so: undefined symbol: opal_show_help
It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_shmem_base_select failed
  --> Returned value -1 instead of OPAL_SUCCESS `
 
and a string of others. I tried building Open MPI by using --disable-dlopen which also did not work. Waiting to hear your thoughts on this. Thanks.

**Comment by Cysu** [comment]
Usually it's due to the mismatch between the openmpi used for compilation and that used for dynamic linking. Could you please check

1. `which mpirun` should point to the openmpi binary you compiled
2. `mpirun --version` should be greater than 1.7.4
3. `ldd caffe/build/install/bin/caffe | grep mpi` should link to the same set of libraries as `ldd $(which mpirun) | grep mpi`

**Comment by Cysu** [comment]
@kalravibhor Please feel free to reopen the issue if there are further problems.
