### ISSUE TITLE
cannot compile caffe

### ISSUE THREAD

**Issue by Bananajia** [ShuangLI59/person_search#55]
hi,
when I compile with cpu, it works perfectly. But when I compile it with GPU, it failed~
My GPU has cuda 8.0 with cudnn 6

/home/thm/xj-use/reid/endtoend/again/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_0000e74c_00000000-5_gather_layer.cpp4.ii".
CMake Error at cuda_compile_generated_gather_layer.cu.o.cmake:266 (message):
  Error generating file
  /home/thm/xj-use/reid/endtoend/again/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_gather_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:91: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_gather_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_gather_layer.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/thm/xj-use/reid/endtoend/again/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_0000e75e_00000000-5_im2col.cpp4.ii".
CMake Error at cuda_compile_generated_im2col.cu.o.cmake:266 (message):
  Error generating file
  /home/thm/xj-use/reid/endtoend/again/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_im2col.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:70: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/util/cuda_compile_generated_im2col.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/util/cuda_compile_generated_im2col.cu.o] Error 1
/home/thm/xj-use/reid/endtoend/again/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_0000e756_00000000-5_base_data_layer.cpp4.ii".
CMake Error at cuda_compile_generated_base_data_layer.cu.o.cmake:266 (message):
  Error generating file
  /home/thm/xj-use/reid/endtoend/again/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_base_data_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:84: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_base_data_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_base_data_layer.cu.o] Error 1
/home/thm/xj-use/reid/endtoend/again/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_0000e743_00000000-5_math_functions.cpp4.ii".
CMake Error at cuda_compile_generated_math_functions.cu.o.cmake:266 (message):
  Error generating file
  /home/thm/xj-use/reid/endtoend/again/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:63: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/util/cuda_compile_generated_math_functions.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/util/cuda_compile_generated_math_functions.cu.o] Error 1
/home/thm/xj-use/reid/endtoend/again/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

/home/thm/xj-use/reid/endtoend/again/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_0000e767_00000000-5_reduction_layer.cpp4.ii".
CMake Error at cuda_compile_generated_reduction_layer.cu.o.cmake:266 (message):
  Error generating file
  /home/thm/xj-use/reid/endtoend/again/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_reduction_layer.cu.o

1 error detected in the compilation of "/tmp/tmpxft_0000e771_00000000-5_mvn_layer.cpp4.ii".
/home/thm/xj-use/reid/endtoend/again/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

src/caffe/CMakeFiles/caffe.dir/build.make:77: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_reduction_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_reduction_layer.cu.o] Error 1
CMake Error at cuda_compile_generated_mvn_layer.cu.o.cmake:266 (message):
  Error generating file
  /home/thm/xj-use/reid/endtoend/again/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_mvn_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:105: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_mvn_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_mvn_layer.cu.o] Error 1
1 error detected in the compilation of "/tmp/tmpxft_0000e77a_00000000-5_hdf5_output_layer.cpp4.ii".
CMake Error at cuda_compile_generated_hdf5_output_layer.cu.o.cmake:266 (message):
  Error generating file
  /home/thm/xj-use/reid/endtoend/again/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_hdf5_output_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:427: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_hdf5_output_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_hdf5_output_layer.cu.o] Error 1
/home/thm/xj-use/reid/endtoend/again/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_0000e782_00000000-5_sigmoid_layer.cpp4.ii".
CMake Error at cuda_compile_generated_sigmoid_layer.cu.o.cmake:266 (message):
  Error generating file
  /home/thm/xj-use/reid/endtoend/again/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_sigmoid_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:98: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_sigmoid_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_sigmoid_layer.cu.o] Error 1
CMakeFiles/Makefile2:240: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed

It seems CUDA version is different~~
Do you have any suggestions?

**Comment by Cysu** [comment]
We only support cudnn-v5 but not cudnn-v6. Please download v5 version and specify it with `-DCUDNN_INCLUDE=/path/to/cudnn/include -DCUDNN_LIBRARY=/path/to/cudnn/lib64/libcudnn.so` cmake options.

**Comment by Bananajia** [comment]
ok! 
I'll reinstall it and see what will happen~~
Thank you!

**Comment by Bananajia** [comment]
we can check our cudnn version using 
cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
if it comes out
#define CUDNN_MAJOR      5
the version is 5

and it worked when I recompile caffe!!
yeah

**Comment by Cysu** [comment]
@Bananajia That's great! Thanks very much for sharing the solution!
