### ISSUE TITLE
sh: 1: cicc: not found

### ISSUE THREAD

**Issue by riokt** [ShuangLI59/person_search#56]
While I do `make` while build the chyton moduls, I got this error.
`cythoning nms/gpu_nms.pyx to nms/gpu_nms.cpp
building 'nms.gpu_nms' extension
/usr/local/bin/nvcc -I/home/rizqi-okta/miniconda2/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda-8.0/include -I/home/rizqi-okta/miniconda2/include/python2.7 -c nms/nms_kernel.cu -o build/temp.linux-x86_64-2.7/nms/nms_kernel.o -arch=sm_35 --ptxas-options=-v -c --compiler-options '-fPIC'
`
`
sh: 1: cicc: not found
error: command '/usr/local/bin/nvcc' failed with exit status 127
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
`

**Comment by Cysu** [comment]
I think you have cuda installed at `/usr/local/cuda-8.0` but currently using `/usr/local/bin/nvcc` instead. Please append
```bash
export PATH=/usr/local/cuda-8.0/bin:$PATH
```
at the end of your `~/.bashrc`, restart the terminal, and recompile the cython modules with `make clean && make`.

**Comment by riokt** [comment]
Thanks @Cysu. But I got new error ehilw build nms.gpu_nms

> building 'nms.gpu_nms' extension
> /usr/local/cuda-8.0/bin/nvcc -I/home/rizqi-okta/miniconda2/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda-8.0/cuda-8.0/include -I/home/rizqi-okta/miniconda2/include/python2.7 -c nms/nms_kernel.cu -o build/temp.linux-x86_64-2.7/nms/nms_kernel.o -arch=sm_35 --ptxas-options=-v -c --compiler-options '-fPIC'
> ptxas info    : 0 bytes gmem
> ptxas info    : Compiling entry function '_Z10nms_kernelifPKfPy' for 'sm_35'
> ptxas info    : Function properties for _Z10nms_kernelifPKfPy                                                                                                                                                                                
>     0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads                                                                                                                                                                           
> ptxas info    : Used 25 registers, 1280 bytes smem, 344 bytes cmem[0], 8 bytes cmem[2]                                                                                                                                                       
> gcc -pthread -B /home/rizqi-okta/miniconda2/compiler_compat -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/rizqi-okta/miniconda2/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda-8.0/cuda-8.0/include -I/home/rizqi-okta/miniconda2/include/python2.7 -c nms/gpu_nms.cpp -o build/temp.linux-x86_64-2.7/nms/gpu_nms.o -Wno-unused-function                                                                                  
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> In file included from /home/rizqi-okta/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
>                  from /home/rizqi-okta/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
>                  from /home/rizqi-okta/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
>                  from nms/gpu_nms.cpp:531:
> /home/rizqi-okta/miniconda2/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
>  #warning "Using deprecated NumPy API, disable it by " \                                                                                                                                                                                     
>   ^
> g++ -pthread -shared -B /home/rizqi-okta/miniconda2/compiler_compat -L/home/rizqi-okta/miniconda2/lib -Wl,-rpath=/home/rizqi-okta/miniconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/nms/nms_kernel.o build/temp.linux-x86_64-2.7/nms/gpu_nms.o -L/usr/local/cuda-8.0/cuda-8.0/lib64 -L/home/rizqi-okta/miniconda2/lib -R/usr/local/cuda-8.0/cuda-8.0/lib64 -lcudart -lpython2.7 -o /home/rizqi-okta/Documents/person_search/lib/nms/gpu_nms.so                                    
> g++: error: unrecognized command line option ‘-R’
> error: command 'g++' failed with exit status 1                                                                                                                                                                                               
> Makefile:2: recipe for target 'all' failed                                                                                                                                                                                                   
> make: *** [all] Error 1

**Comment by Cysu** [comment]
I guess the version of either the g++ or the Cython module is too old. Could you please first try to update Cython? I am not sure if [this issue](https://github.com/h5py/h5py/issues/845) relates to the problem.

**Comment by riokt** [comment]
@Cysu  My Cython is already up-to-date. Maybe you can give me the requirement of Cython version you used.

**Comment by Cysu** [comment]
Mine is Cython 0.26 and g++ 4.8.5, but I think the up-to-date version is also fine.

**Comment by Cysu** [comment]
@riokt Please feel free to reopen the issue if there are further problems.
