### ISSUE TITLE
what is your hardware spec

### ISSUE THREAD

**Issue by jhj7905** [ShuangLI59/person_search#59]
@ShuangLI59

U mentioned on part 3.Training with GPU=0
It will finish in around 18 hours
then, what is your hardware spec ??
i mean cpu and gpu.

**Comment by Cysu** [comment]
We have TitanX (Maxwell, 12GB), Xeon-E5, 512GB memory, and SSD.

**Comment by twmht** [comment]
@Cysu 

I am doing the similar work with pascal 1080 TI (11GB),  but it ran out of memory.

Similar to your work, ROI Polling will produce 128 * 1024 * 7 *7 bounding boxes, I am not sure if 11GB is sufficient.

How is the your memory usage during training?

**Comment by twmht** [comment]
@Cysu 

I set `Train.BATCH_SIZE` to 112, and it works. But I am curious about your settings. For example, when doing inference, you took 2000 rpn proposals and doing convolution on these 2000 rois. But I think TitanX can not handle 2000 rois. Am I right?

**Comment by twmht** [comment]
@Cysu 

by the way, I don't use the pretrained model you provided, I use original caffe implementations provided by here (https://github.com/KaimingHe/deep-residual-networks)

Here is the resnet-50 (http://ethereon.github.io/netscope/#/gist/db945b393d40bfa26006) I used. In the same way, the stem part is from start to `res4c_relu`. 

And my min test scale is 600, which is the same as yours. I have no idea why you can handle 2000 rois when doing inference.

**Comment by twmht** [comment]
@Cysu 

my bad, I have tried the `demo.py` you provided, it takes 300 rois, but only dominates 1.5G memory. What is the magic for memory management in your caffe version?

**Comment by Cysu** [comment]
We use yjxiong/caffe that provides memory optimization.
