### ISSUE TITLE
compile error(common.cpp)

### ISSUE THREAD

**Issue by jjn037** [ShuangLI59/person_search#61]
src/caffe/common.cpp:146:1: error: ‘Caffe’ does not name a type
 Caffe::Caffe()
 ^
src/caffe/common.cpp:177:1: error: ‘Caffe’ does not name a type
 Caffe::~Caffe() {
 ^
src/caffe/common.cpp:184:6: error: ‘Caffe’ has not been declared
 void Caffe::set_random_seed(const unsigned int seed) {
      ^
src/caffe/common.cpp: In function ‘void set_random_seed(unsigned int)’:
src/caffe/common.cpp:187:11: error: ‘Get’ was not declared in this scope
   if (Get().curand_generator_) {
           ^
In file included from ./include/caffe/common.hpp:34:0,

**Comment by Cysu** [comment]
Did you build in CPU_ONLY mode? It is a known issue #21. Please try to compile it with `-DUSE_MPI=ON`.

**Comment by jjn037** [comment]
No, I compiled it with GPU.And I have tried to build in CPU_ONLY and the same error happend.

**Comment by Cysu** [comment]
Could you please show the cmake command you used for compiling the caffe?

**Comment by jjn037** [comment]
You are right,I am so stupid to use a wrong way to compile caffe.Thank you!

**Comment by Cysu** [comment]
Great to know that you have solved it! Please feel free to ask if there are any further problems.

**Comment by jjn037** [comment]
Thank you for your patience


原始邮件
发件人:Tong Xiaonotifications@github.com
收件人:ShuangLI59/person_searchperson_search@noreply.github.com
抄送:姜佳男jiangjianan037@126.com; State changestate_change@noreply.github.com
发送时间:2017年10月15日(周日) 14:23
主题:Re: [ShuangLI59/person_search] compile error(common.cpp) (#61)


Great to know that you have solved it! Please feel free to ask if there are any further problems.

**Comment by chr10003566** [comment]
OK, I meet the same problem as you @jjn037 , But I have not know what's wrong when I compile caffe. So Would you like to tell me what's wrong during compiling caffe?

**Comment by bigyouzi** [comment]
> OK, I meet the same problem as you @jjn037 , But I have not know what's wrong when I compile caffe. So Would you like to tell me what's wrong during compiling caffe?



> OK, I meet the same problem as you @jjn037 , But I have not know what's wrong when I compile caffe. So Would you like to tell me what's wrong during compiling caffe?

How did you solve it at last?
