### ISSUE TITLE
Error with demo.py

### ISSUE THREAD

**Issue by gitrobin** [ShuangLI59/person_search#62]
when I ran python2 tools/demo.py --gpu 0, the following error was encountered.
I1014 13:40:42.606418 19932 net.cpp:1256] blob 159 name det_score data idx 0
I1014 13:40:42.606422 19932 net.cpp:1266] blob 159 name det_score diff idx 2
I1014 13:40:42.606426 19932 net.cpp:1256] blob 160 name pid_prob data idx -1
I1014 13:40:42.606431 19932 net.cpp:1266] blob 160 name pid_prob diff idx -1
I1014 13:40:42.606433 19932 net.cpp:1256] blob 161 name bbox_pred data idx -1
I1014 13:40:42.606437 19932 net.cpp:1266] blob 161 name bbox_pred diff idx -1
I1014 13:40:42.606442 19932 net.cpp:1256] blob 162 name feat_lowdim data idx 0
I1014 13:40:42.606446 19932 net.cpp:1266] blob 162 name feat_lowdim diff idx 0
I1014 13:40:42.606451 19932 net.cpp:1256] blob 163 name feat data idx -1
I1014 13:40:42.606454 19932 net.cpp:1266] blob 163 name feat diff idx -1
I1014 13:40:42.606457 19932 net.cpp:1272] storage memory slot 0 size 3211264
I1014 13:40:42.606462 19932 net.cpp:1272] storage memory slot 1 size 3211264
I1014 13:40:42.606465 19932 net.cpp:1272] storage memory slot 2 size 3211264
I1014 13:40:42.606468 19932 net.cpp:1272] storage memory slot 3 size 8192
I1014 13:40:42.606472 19932 net.cpp:1277] raw memory 304337048 opt memory 10848392
Init end
Traceback (most recent call last):
  File "tools/demo.py", line 114, in <module>
    main(args)
  File "tools/demo.py", line 42, in main
    net = caffe.Net(args.probe_def, args.caffemodel, caffe.TEST)
RuntimeError: basic_string::append

please help me solve this problem。Thanks！

**Comment by Cysu** [comment]
That's weird. It seems that you have already compiled the caffe successfully. You may double check about it by running `caffe/build/install/bin/caffe`. It should print some help messages.

Did you modify anything to the code? Please check `git status` to see if there are any modified files.

**Comment by gitrobin** [comment]
After the errror  emerged，I "add printf("Init end\r\n")"  in net class construcor in  net.cpp   to locate the problem.Even I remove this code, the problem remains。
I have run caffe/build/install/bin/caffe, get the following messages:
I1014 19:14:55.204969 20231 common.cpp:56] You are running caffe compiled with MPI support. Now it's running in non-parallel model
caffe: command line brew
usage: caffe <command> <args>

commands:
  train           train or finetune a model
  test            score a model
  device_query    show GPU diagnostic information
  time            benchmark model execution time

  Flags from /root/person_search/caffe/tools/caffe.cpp:
    -gpu (Run in GPU mode on given device ID.) type: int32 default: -1
    -iterations (The number of iterations to run.) type: int32 default: 50
    -model (The model definition protocol buffer text file..) type: string
      default: ""
    -snapshot (Optional; the snapshot solver state to resume training.)
      type: string default: ""
    -solver (The solver definition protocol buffer text file.) type: string
      default: ""
    -weights (Optional; the pretrained weights to initialize finetuning. Cannot
      be set simultaneously with snapshot.) type: string default: ""

**Comment by Cysu** [comment]
Are there any Chinese characters in the directory path? I am not sure if they would cause the problem.

**Comment by gitrobin** [comment]
No Chinese characters in the directory path. Thefull  path is "/root/person_search". The cudnn library version is 5.1.2. 
I have installed other version caffe on the system,but they are in different paths.  It seems there is something wrong with python.

**Comment by Cysu** [comment]
I suspect it was the c++ code that caused the problem, because `basic_string::append` is a standard function for c++ string. The corresponding net initialization function is at [here](https://github.com/Cysu/caffe/blob/aed38841ae4282d90575186b87c3287620913722/python/caffe/_caffe.cpp#L100-L108). Could you please add some `printf` functions to help find out where the problem is?

**Comment by gitrobin** [comment]
I traced the code. Then I found 
 bool ReadProtoFromBinaryFile(const char* filename, Message* proto) {
  int fd = open(filename, O_RDONLY);
  CHECK_NE(fd, -1) << "File not found: " << filename;
  ZeroCopyInputStream* raw_input = new FileInputStream(fd);
  CodedInputStream* coded_input = new CodedInputStream(raw_input);
  printf("code_input begin\r\n");
  coded_input->SetTotalBytesLimit(kProtoReadBytesLimit, 536870912);
  printf("code_input edn\r\n");
  bool success = proto->ParseFromCodedStream(coded_input);
  printf("parse  end\r\n");
  delete coded_input;
  delete raw_input;
  close(fd);
  return success;
}
 printf("parse  end\r\n") is not run. I think there is something wrong with proto->ParseFromCodedStream(coded_input);  But I cannot find the implemenation of ParseFromCodedStream. Maybe the trained model I have downloaded are corrupt.

**Comment by Cysu** [comment]
Could you please check if the md5 of the downloaded `output/psdb_train/resnet50/resnet50_iter_50000.caffemodel` equals to `b696ecb6c11c21e86384fa96f92a14a0`?

**Comment by gitrobin** [comment]
I checked the md5 of the model ,it is correct. There must be something wrong with  proto->ParseFromCodedStream(coded_input);

**Comment by gitrobin** [comment]
in function ReadProtoFromBinaryFile, I added "if ( !proto ) printf("proto failed\r\n");". Then demo.py worked correctly. I guess some memory must be corrupt.

**Comment by Cysu** [comment]
Well, that's really weird. I have no idea about why it happened. Maybe the memory is corrupted as you said, or the gcc compiler has some bugs. But glad to know that the demo could work under your hack.
