### ISSUE TITLE
在CPU上运行demo.py出现错误：

### ISSUE THREAD

**Issue by XiaoDin9** [ShuangLI59/person_search#63]
W1024 22:16:17.022138  7016 _caffe.cpp:178] Net('D:/Users/dingyong/Downloads/person_search-master/models/psdb/resnet50/eval_probe.prototxt', 1, weights='D:/Users/dingyong/Downloads/person_search-master/output/psdb_train/resnet50/resnet50_iter_50000.caffemodel')
[libprotobuf ERROR C:\Users\guillaume\work\caffe-builder\build_v140_x64\packages\protobuf\protobuf_download-prefix\src\protobuf_download\src\google\protobuf\text_format.cc:298] Error parsing text-format caffe.NetParameter: 1:11: Message type "caffe.NetParameter" has no field named "mem_param".
F1024 22:16:17.138145  7016 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: D:/Users/dingyong/Downloads/person_search-master/models/psdb/resnet50/eval_probe.prototxt
*** Check failure stack trace: ***

**Comment by Cysu** [comment]
It seems that you link to another version of caffe.

**Comment by Cysu** [comment]
@XiaoDin9 Please feel free to reopen the issue if there are further problems.
