### ISSUE TITLE
Error(Training)

### ISSUE THREAD

**Issue by jhj7905** [ShuangLI59/person_search#67]
Hello,
When i trained the model the error occurred as below

I1109 01:10:16.757447  5709 solver.cpp:66] Creating training net from train_net file: models/psdb/resnet50/train.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 1890:24: Message type "caffe.LayerParameter" has no field named "smooth_l1_loss_param".
F1109 01:10:16.758252  5709 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/psdb/resnet50/train.prototxt
*** Check failure stack trace: ***

Can you tell me how to solve this problem?.. i used python2.7

**Comment by Cysu** [comment]
It seems that you link to another version of caffe, which does not have smooth_l1_loss layer.

**Comment by jhj7905** [comment]
@Cysu hmm 
I downloaded the file with git.
but still, error occurred as below.

 32%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/dummy_data_layer.cpp.o
[ 34%] Building CXX object src/caffe/CMakeFiles/caffe.dir/blob.cpp.o
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp:146:1: error: 'Caffe' does not name a type
 Caffe::Caffe()
 ^
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp:177:1: error: 'Caffe' does not name a type
 Caffe::~Caffe() {
 ^
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp:184:6: error: 'Caffe' has not been declared
 void Caffe::set_random_seed(const unsigned int seed) {
      ^
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp: In function 'void set_random_seed(unsigned int)':
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp:187:11: error: 'Get' was not declared in this scope
   if (Get().curand_generator_) {
           ^
In file included from /home/jhj7905/opencv_search/person_search/caffe/include/caffe/common.hpp:34:0,
                 from /home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp:5:
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp:188:70: error: 'curand_generator' was not declared in this scope
     CURAND_CHECK(curandSetPseudoRandomGeneratorSeed(curand_generator(),
                                                                      ^
/home/jhj7905/opencv_search/person_search/caffe/include/caffe/util/device_alternate.hpp:64:29: note: in definition of macro 'CURAND_CHECK'
     curandStatus_t status = condition; \
                             ^
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp:190:60: error: 'curand_generator' was not declared in this scope
     CURAND_CHECK(curandSetGeneratorOffset(curand_generator(), 0));
                                                            ^
/home/jhj7905/opencv_search/person_search/caffe/include/caffe/util/device_alternate.hpp:64:29: note: in definition of macro 'CURAND_CHECK'
     curandStatus_t status = condition; \
                             ^
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp:199:7: error: 'Get' was not declared in this scope
   Get().random_generator_.reset(new RNG(seed));
       ^
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp:199:37: error: expected type-specifier before 'RNG'
   Get().random_generator_.reset(new RNG(seed));
                                     ^
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp: At global scope:
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp:202:6: error: 'Caffe' has not been declared
 void Caffe::SetDevice(const int device_id) {
      ^
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp: In function 'void SetDevice(int)':
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp:206:42: error: 'Get' was not declared in this scope
   if (current_device == device_id && Get().cublas_handle_ && Get().curand_generator_) {
                                          ^
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp:212:11: error: 'Get' was not declared in this scope
   if (Get().cublas_handle_) CUBLAS_CHECK(cublasDestroy(Get().cublas_handle_));
           ^
/home/jhj7905/opencv_search/person_search/caffe/src/caffe/common.cpp:213:11: error: 'Get' was not declared in this scope
   if (Get().curand_generator_) {

how to solve thi problem?
thank you in advance
