### ISSUE TITLE
How to modify the train.prototxt to train the network

### ISSUE THREAD

**Issue by jhj7905** [ShuangLI59/person_search#68]
@Cysu  
Hi,
Now, I compiled person_search successfully, now i have trained the network.
when i read your train.prototxt, there are 5532 query person for training in Ln1939 and Ln3093(Ln-> Line)
then if i increase the number of training db to train the network, could you tell me how to modify the train.prototxt? i think i modify the 5532 to 6000(example)... is it right?
thank you in advance

**Comment by Cysu** [comment]
Yes, just modify the 5532 to 6000, and make sure the labels provided by your dataset is in between 0-5999.

**Comment by jhj7905** [comment]
@Cysu 
I added the images(ex..s1000.png) on path(/Image/SSM), and modified the Train.mat, Person.mat,Images.mat and finally changed 5532 to 6000 in train.prototxt.
When I ran the experiments/scripts/train.sh 0 --set EXP_DIR resnet50, error occured like below
  File "tools/train_net.py", line 121, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "tools/train_net.py", line 74, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "tools/train_net.py", line 71, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/jhj7905/opencv_search/person_search/tools/../lib/fast_rcnn/train.py", line 87, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File "/home/jhj7905/opencv_search/person_search/tools/../lib/roi_data_layer/roidb.py", line 28, in prepare_roidb
    roidb[i]['image'] = imdb.image_path_at(i)
IndexError: list index out of range

Questions as below
Q1. .png file was possible to read?
Q2. Is there anything i need to change the source code?
Q3. How to solve about error...

thank you in advance

**Comment by Cysu** [comment]
@jhj7905 Sorry for the late reply.

1. PNG file should be readable.
2. It should be good to run the code after your modifications. Do you encounter some problems?
