### ISSUE TITLE
caffe compile problem

### ISSUE THREAD

**Issue by wjwstate** [ShuangLI59/person_search#70]
i use the server in laboratory.when i compile the caffe i get the problem like this:

**one server:**

wujianwen@hadoop:/mnt/wujianwen/person_search/caffe/build$ cmake .. -DUSE_MPI=ON -DCUDNN_INCLUDE=/mnt/wujianwen/cuda/include -DCUDNN_LIBRARY=/mnt/wujianwen/cuda/lib64/libcudnn.so
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
--   thread
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/libsnappy.so)
-- CUDA detected: 8.0
-- Found cuDNN (include: /mnt/wujianwen/cuda/include, library: /mnt/wujianwen/cuda/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_52
-- Cuda + Boost 1.55: Applying noinline work around
-- OpenCV found (/usr/share/OpenCV)
-- Found Atlas (include: /usr/include, library: /usr/lib/libatlas.so)
-- NumPy ver. 1.13.3 found (include: /usr/local/lib/python2.7/dist-packages/numpy/core/include)
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   python
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   <TODO> (Caffe doesn't declare its version in headers)
--   Git               :   v0.9999-1625-gaed3884
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.55)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.6.1)
--   lmdb              :   Yes (ver. 0.9.14)
--   Snappy            :   Yes (ver. 1.1.2)
--   LevelDB           :   Yes (ver. 1.17)
--   OpenCV            :   Yes (ver. 2.4.9)
--   CUDA              :   Yes (ver. 8.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_52
--   cuDNN             :   Yes
-- 
-- Python:
--   Interpreter       :   /usr/bin/python2.7 (ver. 2.7.9)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.9)
--   NumPy             :   /usr/local/lib/python2.7/dist-packages/numpy/core/include (ver 1.13.3)
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /mnt/wujianwen/person_search/caffe/build/install
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/wujianwen/person_search/caffe/build
wujianwen@lmc:~/files/person_search/caffe/build$ make -j8 && make install
[  1%] Running C++/Python protocol buffer compiler on /home/wujianwen/files/person_search/caffe/src/caffe/proto/caffe.proto
Scanning dependencies of target proto
[  1%] Building CXX object src/caffe/CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
........................................
........................................
........................................
........................................
[ 77%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_pooling_layer.cpp.o
[ 77%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/labeled_matching_layer.cpp.o
[ 78%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/exp_layer.cpp.o
In file included from /home/wujianwen/files/person_search/caffe/include/caffe/util/device_alternate.hpp:40:0,
                 from /home/wujianwen/files/person_search/caffe/include/caffe/common.hpp:34,
                 from /home/wujianwen/files/person_search/caffe/include/caffe/blob.hpp:8,
                 from /home/wujianwen/files/person_search/caffe/include/caffe/filler.hpp:10,
                 from /home/wujianwen/files/person_search/caffe/src/caffe/layers/cudnn_conv_layer.cpp:5:
/home/wujianwen/files/person_search/caffe/include/caffe/util/cudnn.hpp: In instantiation of ‘void caffe::cudnn::createFilterDesc(cudnnFilterStruct**, int, int, int, int) [with Dtype = float; cudnnFilterDescriptor_t = cudnnFilterStruct*]’:
/home/wujianwen/files/person_search/caffe/src/caffe/layers/cudnn_conv_layer.cpp:82:39:   required from ‘void caffe::CuDNNConvolutionLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’
/home/wujianwen/files/person_search/caffe/src/caffe/layers/cudnn_conv_layer.cpp:247:1:   required from here
/home/wujianwen/files/person_search/caffe/include/caffe/util/cudnn.hpp:95:71: error: too many arguments to function ‘cudnnStatus_t cudnnSetFilter4dDescriptor(cudnnFilterDescriptor_t, cudnnDataType_t, int, int, int, int)’
                                          CUDNN_TENSOR_NCHW, n, c, h, w));
                                                                       ^
/home/wujianwen/files/person_search/caffe/include/caffe/util/cudnn.hpp:15:28: note: in definition of macro ‘CUDNN_CHECK’
     cudnnStatus_t status = condition; \
                            ^
In file included from /home/wujianwen/files/person_search/caffe/include/caffe/util/cudnn.hpp:5:0,
                 from /home/wujianwen/files/person_search/caffe/include/caffe/util/device_alternate.hpp:40,
                 from /home/wujianwen/files/person_search/caffe/include/caffe/common.hpp:34,
                 from /home/wujianwen/files/person_search/caffe/include/caffe/blob.hpp:8,
                 from /home/wujianwen/files/person_search/caffe/include/caffe/filler.hpp:10,
                 from /home/wujianwen/files/person_search/caffe/src/caffe/layers/cudnn_conv_layer.cpp:5:
/usr/local/include/cudnn.h:303:27: note: declared here
 cudnnStatus_t CUDNNWINAPI cudnnSetFilter4dDescriptor(
                           ^
In file included from /home/wujianwen/files/person_search/caffe/include/caffe/util/device_alternate.hpp:40:0,
                 from /home/wujianwen/files/person_search/caffe/include/caffe/common.hpp:34,
                 from /home/wujianwen/files/person_search/caffe/include/caffe/blob.hpp:8,
                 from /home/wujianwen/files/person_search/caffe/include/caffe/filler.hpp:10,
                 from /home/wujianwen/files/person_search/caffe/src/caffe/layers/cudnn_conv_layer.cpp:5:
/home/wujianwen/files/person_search/caffe/include/caffe/util/cudnn.hpp: In instantiation of ‘void caffe::cudnn::createFilterDesc(cudnnFilterStruct**, int, int, int, int) [with Dtype = double; cudnnFilterDescriptor_t = cudnnFilterStruct*]’:
/home/wujianwen/files/person_search/caffe/src/caffe/layers/cudnn_conv_layer.cpp:82:39:   required from ‘void caffe::CuDNNConvolutionLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’
/home/wujianwen/files/person_search/caffe/src/caffe/layers/cudnn_conv_layer.cpp:247:1:   required from here
/home/wujianwen/files/person_search/caffe/include/caffe/util/cudnn.hpp:95:71: error: too many arguments to function ‘cudnnStatus_t cudnnSetFilter4dDescriptor(cudnnFilterDescriptor_t, cudnnDataType_t, int, int, int, int)’
                                          CUDNN_TENSOR_NCHW, n, c, h, w));
                                                                       ^
/home/wujianwen/files/person_search/caffe/include/caffe/util/cudnn.hpp:15:28: note: in definition of macro ‘CUDNN_CHECK’
     cudnnStatus_t status = condition; \
                            ^
In file included from /home/wujianwen/files/person_search/caffe/include/caffe/util/cudnn.hpp:5:0,
                 from /home/wujianwen/files/person_search/caffe/include/caffe/util/device_alternate.hpp:40,
                 from /home/wujianwen/files/person_search/caffe/include/caffe/common.hpp:34,
                 from /home/wujianwen/files/person_search/caffe/include/caffe/blob.hpp:8,
                 from /home/wujianwen/files/person_search/caffe/include/caffe/filler.hpp:10,
                 from /home/wujianwen/files/person_search/caffe/src/caffe/layers/cudnn_conv_layer.cpp:5:
/usr/local/include/cudnn.h:303:27: note: declared here
 cudnnStatus_t CUDNNWINAPI cudnnSetFilter4dDescriptor(
                           ^
src/caffe/CMakeFiles/caffe.dir/build.make:2042: recipe for target 'src/caffe/CMakeFiles/caffe.dir/layers/cudnn_conv_layer.cpp.o' failed
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/cudnn_conv_layer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:187: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

-------------------------------------------------------------------------------------------------------------------

**another server**:
wujianwen@lmc:~/files/person_search/caffe/build$ cmake .. -DUSE_MPI=ON -DCUDNN_INCLUDE=/home/wujianwen/files/cuda/include -DCUDNN_LIBRARY=/home/wujianwen/files/cuda/lib64/libcudnn.so
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
--   thread
-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.so)
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/libsnappy.so)
-- CUDA detected: 8.0
-- Found cuDNN (include: /home/wujianwen/files/cuda/include, library: /home/wujianwen/files/cuda/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_52
-- Cuda + Boost 1.55: Applying noinline work around
-- OpenCV found (/usr/share/OpenCV)
-- Found Atlas (include: /usr/include, library: /usr/lib/libatlas.so)
-- NumPy ver. 1.11.2 found (include: /usr/local/lib/python2.7/dist-packages/numpy/core/include)
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   python
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   <TODO> (Caffe doesn't declare its version in headers)
--   Git               :   v0.9999-1625-gaed3884
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.55)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.6.1)
--   lmdb              :   Yes (ver. 0.9.14)
--   Snappy            :   Yes (ver. 1.1.2)
--   LevelDB           :   Yes (ver. 1.17)
--   OpenCV            :   Yes (ver. 2.4.9)
--   CUDA              :   Yes (ver. 8.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_52
--   cuDNN             :   Yes
-- 
-- Python:
--   Interpreter       :   /usr/bin/python2.7 (ver. 2.7.9)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.9)
--   NumPy             :   /usr/local/lib/python2.7/dist-packages/numpy/core/include (ver 1.11.2)
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /home/wujianwen/files/person_search/caffe/build/install
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wujianwen/files/person_search/caffe/build
wujianwen@hadoop:/mnt/wujianwen/person_search/caffe/build$ make -j8 && make install[  1%] Running C++/Python protocol buffer compiler on /mnt/wujianwen/person_search/caffe/src/caffe/proto/caffe.proto
Scanning dependencies of target proto
[  1%] Building CXX object src/caffe/CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
Linking CXX static library ../../lib/libproto.a
[  1%] Built target proto
[  1%] [  2%] [  2%] [  2%] [  4%] [  5%] [  7%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_conv_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_im2col.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o
[  7%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_silence_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_scatter_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_power_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_exp_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_relu_layer.cu.o
/mnt/wujianwen/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

/mnt/wujianwen/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_0000781e_00000000-5_math_functions.cpp4.ii".
1 error detected in the compilation of "/tmp/tmpxft_00007803_00000000-5_power_layer.cpp4.ii".
CMake Error at cuda_compile_generated_math_functions.cu.o.cmake:264 (message):
  Error generating file
  /mnt/wujianwen/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:63: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMake Error at cuda_compile_generated_power_layer.cu.o.cmake:264 (message):
  Error generating file
  /mnt/wujianwen/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_power_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:95: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_power_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_power_layer.cu.o] Error 1
/mnt/wujianwen/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_00007827_00000000-5_im2col.cpp4.ii".
CMake Error at cuda_compile_generated_im2col.cu.o.cmake:264 (message):
  Error generating file
  /mnt/wujianwen/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_im2col.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:55: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_im2col.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_im2col.cu.o] Error 1
/mnt/wujianwen/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

/mnt/wujianwen/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

/mnt/wujianwen/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_00007845_00000000-5_cudnn_relu_layer.cpp4.ii".
CMake Error at cuda_compile_generated_cudnn_relu_layer.cu.o.cmake:264 (message):
  Error generating file
  /mnt/wujianwen/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_relu_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:79: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_relu_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_relu_layer.cu.o] Error 1
1 error detected in the compilation of "/tmp/tmpxft_0000783b_00000000-5_exp_layer.cpp4.ii".
1 error detected in the compilation of "/tmp/tmpxft_00007831_00000000-5_silence_layer.cpp4.ii".
CMake Error at cuda_compile_generated_silence_layer.cu.o.cmake:264 (message):
  Error generating file
  /mnt/wujianwen/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_silence_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:87: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_silence_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_silence_layer.cu.o] Error 1
CMake Error at cuda_compile_generated_exp_layer.cu.o.cmake:264 (message):
  Error generating file
  /mnt/wujianwen/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_exp_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:71: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_exp_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_exp_layer.cu.o] Error 1
/mnt/wujianwen/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_0000780c_00000000-5_conv_layer.cpp4.ii".
CMake Error at cuda_compile_generated_conv_layer.cu.o.cmake:264 (message):
  Error generating file
  /mnt/wujianwen/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_conv_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:471: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_conv_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_conv_layer.cu.o] Error 1
/mnt/wujianwen/person_search/caffe/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_0000784e_00000000-5_scatter_layer.cpp4.ii".
CMake Error at cuda_compile_generated_scatter_layer.cu.o.cmake:264 (message):
  Error generating file
  /mnt/wujianwen/person_search/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_scatter_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:103: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_scatter_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_scatter_layer.cu.o] Error 1
CMakeFiles/Makefile2:187: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Cysu** [comment]
It seems that you are using another version of CUDNN. Please try to use cudnn-v5.1, and compile with
```
cmake .. -DUSE_MPI=ON -DCUDNN_INCLUDE=/path/to/cudnn-v5.1/include -DCUDNN_LIBRARY=/path/to/cudnn-v5.1/lib64/libcudnn.so
```

**Comment by XiaoDin9** [comment]
我也遇到了编译caffe的问题，在输入cmake .. -DUSE_MPI=ON      -DCUDNN_INCLUDE=/home/group2/cuda/include -DCUDNN_LIBRARY=/home/group2/cuda/lib64/libcudnn.so, 出现如下的错误：
See also "/home/group2/person_search-master/caffe/build/CMakeFiles/CMakeOutput.log".
See also "/home/group2/person_search-master/caffe/build/CMakeFiles/CMakeError.log".
进入错误日志文件：CMakeError.log
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/group2/person_search-master/caffe/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec582802986/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec582802986.dir/build.make CMakeFiles/cmTryCompileExec582802986.dir/build
make[1]: Entering directory `/home/group2/person_search-master/caffe/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/group2/person_search-master/caffe/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec582802986.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTryCompileExec582802986.dir/CheckSymbolExists.c.o   -c /home/group2/person_search-master/caffe/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTryCompileExec582802986
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec582802986.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTryCompileExec582802986.dir/CheckSymbolExists.c.o  -o cmTryCompileExec582802986 -rdynamic
CMakeFiles/cmTryCompileExec582802986.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[1]: *** [cmTryCompileExec582802986] Error 1
make[1]: Leaving directory `/home/group2/person_search-master/caffe/build/CMakeFiles/CMakeTmp'
make: *** [cmTryCompileExec582802986/fast] Error 2

File /home/group2/person_search-master/caffe/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/group2/person_search-master/caffe/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec2085511034/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec2085511034.dir/build.make CMakeFiles/cmTryCompileExec2085511034.dir/build
make[1]: Entering directory `/home/group2/person_search-master/caffe/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/group2/person_search-master/caffe/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec2085511034.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTryCompileExec2085511034.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-2.8/Modules/CheckFunctionExists.c
Linking C executable cmTryCompileExec2085511034
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec2085511034.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTryCompileExec2085511034.dir/CheckFunctionExists.c.o  -o cmTryCompileExec2085511034 -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [cmTryCompileExec2085511034] Error 1
make[1]: Leaving directory `/home/group2/person_search-master/caffe/build/CMakeFiles/CMakeTmp'
make: *** [cmTryCompileExec2085511034/fast] Error 2
希望能得到你的帮助，谢谢！

**Comment by Cysu** [comment]
@XiaoDin9 Seems to be the compiler problem. Please try to use `CC=gcc CXX=g++ cmake ..` and see if it helps.
