### ISSUE TITLE
Demo.py error

### ISSUE THREAD

**Issue by FredHuang16** [ShuangLI59/person_search#73]
Hi,

Looking for help. I managed to successfully build and install OpenMPI 1.8.8 on Ubuntu 14.04 . However when I try and run the demo, I get the following error :+1: 

It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_paffinity_base_select failed
  --> Returned value -13 instead of OPAL_SUCCESS
--------------------------------------------------------------------------
[dgx-1-2:02165] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file runtime/orte_init.c at line 77
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: orte_init failed
  --> Returned "Not found" (-13) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** before MPI was initialized
*** MPI_ERRORS_ARE_FATAL (your MPI job will now abort)
[dgx-1-2:2165] Abort before MPI_INIT completed successfully; not able to guarantee that all other processes were killed!

The Linking seems right:
haha@dgx-1-2:~/haha/person_search$ which mpirun
/usr/local/bin/mpirun
haha@dgx-1-2:~/haha/person_search$ ldd caffe/build/install/bin/caffe | grep mpi
	libmpi_cxx.so.1 => /usr/local/lib/libmpi_cxx.so.1 (0x00007f8ed4b32000)
	libmpi.so.1 => /usr/local/lib/libmpi.so.1 (0x00007f8ed4858000)

**Comment by XiaoDin9** [comment]
你好！我想问一下作者你这个项目的代码你是之前有跑通过是嘛？我最近也在做行人重识别的课题，但是我一直折腾你的代码，出现了各种的错误，不是编译caffe出错就是在cython这块儿编译有错，你可以把你的邮箱发我一下好嘛，这样解决问题更直接更高效一些，我一直调错断断续续的发了半个月啦，还是不能跑起来，希望能得到作者的真心帮助，本人在行人重识别这块儿刚起步算是菜鸟，静等你的消息！

**Comment by Cysu** [comment]
@FredHuang16 Please refer to #54 and see if the comments there solve your problem.

**Comment by Cysu** [comment]
@XiaoDin9 Please try to compile official caffe with cmake first. Ours should have only a few modifications on that.

**Comment by 435981572** [comment]
hello ,are you in China ?I 'am in Shaanxi Provence ,recently ,I can't download the dataset of this paper ,could you send me the dataset ?thanks a lot .
