### ISSUE TITLE
The ResNet50 model

### ISSUE THREAD

**Issue by chenchuanch** [ShuangLI59/person_search#75]
Hi, 
The network in person_search project is ResNet50, but it is different to the ResNet50 downloaded from [https://github.com/KaimingHe/deep-residual-networks](https://github.com/KaimingHe/deep-residual-networks). Why use this ResNet50 model rather than Kaiming's model? What's the main difference between two model? Can someone tell me reasons?

**Comment by Cysu** [comment]
We started the project before Kaiming released the model. The performance on ImageNet could be different.

**Comment by chenchuanch** [comment]
Thank you. Great work~
