### ISSUE TITLE
Install caffe under the anaconda environment.

### ISSUE THREAD

**Issue by Lan1991Xu** [ShuangLI59/person_search#76]
Hi , Thanks for provide the code. Currently I am try to install caffer. My platform is Centos7, cuda8.0,  cudnn5.1. I have follow the readme, but I get the problem not find Atlas. I have check the libatlas is in the anaconda/lib. Could you give me any suggestion about this situation. It seems when install caffe, it not use the anaconda/lib. I rember the offical caffe install need the Makefile.config, I can set the envirionment in this file.

**Comment by Cysu** [comment]
I recommend not adding anaconda libs to LD_LIBRARY_PATH, just add its bin directory to the PATH, in order to use its python.

Maybe you could install OpenBLAS and use -DBLAS=Open when cmake.

**Comment by Cysu** [comment]
@Lan1991Xu Please feel free to reopen the issue if there are further questions.
