### ISSUE TITLE
external buffer 

### ISSUE THREAD

**Issue by lijie-vipl-ict** [ShuangLI59/person_search#77]
hi,shuang,recently,i have a work meet a batch problem same to you guys' work,you guys have perfectly solved it ,i'm really confused about it,so i want to ask u ,how, LUT and CQ interact with your caffenetwork.
thank u,look for your answer

**Comment by Cysu** [comment]
I think you’ve already figured out the answer that they are implemented in LabeledMatching and UnlabeledMatching layers.
