### ISSUE TITLE
在LabeledMatching这个层里面的blob执行一次初始化之后，内存就不会被释放了？

### ISSUE THREAD

**Issue by lijie-vipl-ict** [ShuangLI59/person_search#78]
在LabeledMatching这个层里面的blob执行一次初始化之后，内存就不会被释放了？可以一直记录一些feature的信息吗？

**Comment by lijie-vipl-ict** [comment]
@Cysu @ningzhou @ShuangLI59

**Comment by Cysu** [comment]
Your question is “During training, are the blobs in LabeledMatching layer released after initialization?”.

The answer is they will not be released. Your understanding is correct.

**Comment by lijie-vipl-ict** [comment]
Thank u for your answer. i benifit a lot from your work. what chat tools do u use，can we add a WeChat？发自我的华为手机-------- 原始邮件 --------主题：Re: [ShuangLI59/person_search] 在LabeledMatching这个层里面的blob执行一次初始化之后，内存就不会被释放了？ (#78)发件人：Tong Xiao 收件人：ShuangLI59/person_search 抄送：lijie-vipl-ict ,Author Your question is “During training, are the blobs in LabeledMatching layer released after initialization?”.
The answer is they will not be released. Your understanding is correct.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ShuangLI59/person_search","title":"ShuangLI59/person_search","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ShuangLI59/person_search"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Cysu in #78: Your question is “During training, are the blobs in LabeledMatching layer released after initialization?”.\r\n\r\nThe answer is they will not be released. Your understanding is correct."}],"action":{"name":"View Issue","url":"https://github.com/ShuangLI59/person_search/issues/78#issuecomment-353789519"}}}
