### ISSUE TITLE
why id_accuracy=-nan

### ISSUE THREAD

**Issue by melinni** [ShuangLI59/person_search#80]
Is there any thing wrong?
dataset?
train net?
or base_lr? 0.001 or 0.0001

**Comment by Cysu** [comment]
No, nothing wrong. Just because some images do not contain labeled identities.

**Comment by melinni** [comment]
Thanks.

发送自 Windows 10 版邮件应用

发件人: Tong Xiao
发送时间: 2017年12月29日 14:39
收件人: ShuangLI59/person_search
抄送: melinni; Author
主题: Re: [ShuangLI59/person_search] why id_accuracy=-nan (#80)

No, nothing wrong. Just because some images do not contain labeled identities.
