### ISSUE TITLE
Run training on PRW dataset

### ISSUE THREAD

**Issue by Saadiabatool** [ShuangLI59/person_search#81]
I am trying to run code for prw dataset, for this i updated images.mat and persons.mat, but there is no description of bounding boxes against train and test.mat files in PRW.
Please help me, either updates in lib/dataset required or some other workaround.

**Comment by Cysu** [comment]
@Saadiabatool these are two different datasets, with very different raw formats. Welcome any pull requests for PRW!

**Comment by Saadiabatool** [comment]
Preprocessing part is done, any suggestions to improve accuracy of the model ??

**Comment by Cysu** [comment]
@Saadiabatool It's hard to say without knowing experiment results. 932 identities should be fine.
