### ISSUE TITLE
A error

### ISSUE THREAD

**Issue by gcy2231192** [ShuangLI59/person_search#83]
Hi @Cysu and @ShuangLI59 
Now, when  experiments/scripts/eval_test.sh resnet50 50000 resnet50 was run, I got such error. but I don't have any idea. Could you tell me how to solve it ? Thank you very much!!!

error:
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0105 10:55:15.645474  5230 common.cpp:114] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
Called with args:
Namespace(blob_names='feat', caffemodel='output/psdb_train/resnet50/resnet50_iter_50000.caffemodel', cfg_file='experiments/cfgs/resnet50.yml', det_thresh=0.5, eval_only=False, gallery_def='models/psdb/resnet50/eval_gallery.prototxt', gallery_size=100, gpus='-1', imdb_name='psdb_test', probe_def='models/psdb/resnet50/eval_probe.prototxt', set_cfgs=['EXP_DIR', 'resnet50'], use_gt=False, wait=True)
Using config:
{'DATA_DIR': '/home/wsn/person_search/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'resnet50',
 'GPU_ID': -1,
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/wsn/person_search/models/pascal_voc',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/wsn/person_search',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.4,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'MAX_SIZE': 1000,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': False}
[wsn-Inspiron-3420:05230] *** Process received signal ***
[wsn-Inspiron-3420:05230] Signal: Aborted (6)
[wsn-Inspiron-3420:05230] Signal code:  (-6)
[wsn-Inspiron-3420:05230] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f099880d390]
[wsn-Inspiron-3420:05230] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f0998467428]
[wsn-Inspiron-3420:05230] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f099846902a]
[wsn-Inspiron-3420:05230] [ 3] /usr/lib/x86_64-linux-gnu/libglog.so.0(+0x9e49)[0x7f098925de49]
[wsn-Inspiron-3420:05230] [ 4] /usr/lib/x86_64-linux-gnu/libglog.so.0(+0xb5cd)[0x7f098925f5cd]
[wsn-Inspiron-3420:05230] [ 5] /usr/lib/x86_64-linux-gnu/libglog.so.0(_ZN6google10LogMessage9SendToLogEv+0x283)[0x7f0989261433]
[wsn-Inspiron-3420:05230] [ 6] /usr/lib/x86_64-linux-gnu/libglog.so.0(_ZN6google10LogMessage5FlushEv+0xbb)[0x7f098925f15b]
[wsn-Inspiron-3420:05230] [ 7] /usr/lib/x86_64-linux-gnu/libglog.so.0(_ZN6google15LogMessageFatalD2Ev+0xe)[0x7f0989261e1e]
[wsn-Inspiron-3420:05230] [ 8] /home/wsn/person_search/caffe/build/lib/libcaffe.so(_ZN5caffe5Caffe9SetDeviceEi+0x50)[0x7f098a7cf520]
[wsn-Inspiron-3420:05230] [ 9] /home/wsn/person_search/tools/../caffe/python/caffe/_caffe.so(_ZN5boost6python7objects23caller_py_function_implINS0_6detail6callerIPFviENS0_21default_call_policiesENS_3mpl7vector2IviEEEEEclEP7_objectSE_+0x61)[0x7f098abebee1]
[wsn-Inspiron-3420:05230] [10] /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0(_ZNK5boost6python7objects8function4callEP7_objectS4_+0x26d)[0x7f0989dd25cd]
[wsn-Inspiron-3420:05230] [11] /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0(+0x297c8)[0x7f0989dd27c8]
[wsn-Inspiron-3420:05230] [12] /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0(_ZN5boost6python21handle_exception_implENS_9function0IvEE+0x73)[0x7f0989dda613]
[wsn-Inspiron-3420:05230] [13] /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0(+0x26999)[0x7f0989dcf999]
[wsn-Inspiron-3420:05230] [14] python2(PyObject_Call+0x43)[0x4b0c93]
[wsn-Inspiron-3420:05230] [15] python2(PyEval_EvalFrameEx+0x602f)[0x4c9f9f]
[wsn-Inspiron-3420:05230] [16] python2(PyEval_EvalCodeEx+0x255)[0x4c2705]
[wsn-Inspiron-3420:05230] [17] python2(PyEval_EvalFrameEx+0x686f)[0x4ca7df]
[wsn-Inspiron-3420:05230] [18] python2(PyEval_EvalCodeEx+0x255)[0x4c2705]
[wsn-Inspiron-3420:05230] [19] python2(PyEval_EvalCode+0x19)[0x4c24a9]
[wsn-Inspiron-3420:05230] [20] python2[0x4f19ef]
[wsn-Inspiron-3420:05230] [21] python2(PyRun_FileExFlags+0x82)[0x4ec372]
[wsn-Inspiron-3420:05230] [22] python2(PyRun_SimpleFileExFlags+0x191)[0x4eaaf1]
[wsn-Inspiron-3420:05230] [23] python2(Py_Main+0x6c8)[0x49e208]
[wsn-Inspiron-3420:05230] [24] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f0998452830]
[wsn-Inspiron-3420:05230] [25] python2(_start+0x29)[0x49da59]
[wsn-Inspiron-3420:05230] *** End of error message ***

I'm looking forward your answer,in a really big hurry,and thank you!!!

**Comment by 435981572** [comment]
hello ,are you in China ?I 'am in Shaanxi Provence ,recently ,I can't download the dataset of this paper ,could you send me the dataset ?thanks a lot .

**Comment by Saadiabatool** [comment]
Seems like there is memory issue

**Comment by Cysu** [comment]
@gcy2231192 In the second line of error message:
```
Cannot use GPU in CPU-only Caffe
```
Please compile it with GPU enabled.
