### ISSUE TITLE
about dataset 

### ISSUE THREAD

**Issue by 435981572** [ShuangLI59/person_search#86]
hello ,I'am from xi'an polytechnic university ,I'am a fresh in person re- identification .thanks for release your paper code .recently ,I want to run this code ,but I can't download your dataset though this HongKong  website you given ,so ,could you upload this dataset in mainland website ,and write note in zhihu ?and ,my e-mail is 435981572@qq.com.thanks a lot .

**Comment by Cysu** [comment]
@435981572 Please send email to me, through your institution email. Thanks.
