### ISSUE TITLE
caffe compile error!!

### ISSUE THREAD

**Issue by 695874419** [ShuangLI59/person_search#89]
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/wty/Downloads/person_search-master/caffe/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_7a828/fast"
/usr/bin/make -f CMakeFiles/cmTC_7a828.dir/build.make CMakeFiles/cmTC_7a828.dir/build
make[1]: Entering directory '/home/wty/Downloads/person_search-master/caffe/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_7a828.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_7a828.dir/CheckSymbolExists.c.o   -c /home/wty/Downloads/person_search-master/caffe/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_7a828
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_7a828.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_7a828.dir/CheckSymbolExists.c.o  -o cmTC_7a828 -rdynamic 
CMakeFiles/cmTC_7a828.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_7a828.dir/build.make:97: recipe for target 'cmTC_7a828' failed
make[1]: *** [cmTC_7a828] Error 1
make[1]: Leaving directory '/home/wty/Downloads/person_search-master/caffe/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_7a828/fast' failed
make: *** [cmTC_7a828/fast] Error 2

File /home/wty/Downloads/person_search-master/caffe/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/wty/Downloads/person_search-master/caffe/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_2fb45/fast"
/usr/bin/make -f CMakeFiles/cmTC_2fb45.dir/build.make CMakeFiles/cmTC_2fb45.dir/build
make[1]: Entering directory '/home/wty/Downloads/person_search-master/caffe/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_2fb45.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_2fb45.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_2fb45
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2fb45.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_2fb45.dir/CheckFunctionExists.c.o  -o cmTC_2fb45 -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_2fb45.dir/build.make:97: recipe for target 'cmTC_2fb45' failed
make[1]: *** [cmTC_2fb45] Error 1
make[1]: Leaving directory '/home/wty/Downloads/person_search-master/caffe/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_2fb45/fast' failed
make: *** [cmTC_2fb45/fast] Error 2

**Comment by Cysu** [comment]
@695874419 Not sure why it happened. Can you attach the cmake reports?
