### ISSUE TITLE
cudnn and cuda version 

### ISSUE THREAD

**Issue by blasheroy** [ShuangLI59/person_search#9]
may i know which cudnn and cuda version is compatible with the codes?

**Comment by Cysu** [comment]
It's compatible with cuda >= 7.0 and cudnn >= 4.

**Comment by blasheroy** [comment]
Thank you for your fast response.
I'm using cuda 7.5 and cudnn 5.0, but when I try to execute make pycaffe, it shows error: too few arguments to function ‘cudnnStatus_t cudnnSetPooling2dDescriptor(cudnnPoolingDescriptor_t, cudnnPoolingMode_t, cudnnNanPropagation_t, int, int, int, int, int, int)’
I had attached the screenshot of terminal output, please give me some advice to solve this error. 
![screenshot from 2016-10-26 10 08 47](https://cloud.githubusercontent.com/assets/18228712/19710986/ff75a71e-9b64-11e6-87d3-0f1147fef0b3.png)

**Comment by blasheroy** [comment]
Thank you.
