### ISSUE TITLE
when make -j8 ,make error!!

### ISSUE THREAD

**Issue by 695874419** [ShuangLI59/person_search#90]
[ 79%] Building CXX object src/caffe/CMakeFiles/caffe.dir/syncedmem.cpp.o
[ 80%] Building CXX object src/caffe/CMakeFiles/caffe.dir/internal_thread.cpp.o
[ 80%] Building CXX object src/caffe/CMakeFiles/caffe.dir/solver.cpp.o
[ 80%] Linking CXX shared library ../../lib/libcaffe.so
/usr/bin/ld: /home/software_mount/wty/local_install/lib/libgflags.a(gflags.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/software_mount/wty/local_install/lib/libgflags.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/caffe/CMakeFiles/caffe.dir/build.make:3002: recipe for target 'lib/libcaffe.so' failed
make[2]: *** [lib/libcaffe.so] Error 1
CMakeFiles/Makefile2:240: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Cysu** [comment]
@695874419 Please compile libgflags to share objects (.so files)
