### ISSUE TITLE
Mat File struct meaning

### ISSUE THREAD

**Issue by dasheyuan** [ShuangLI59/person_search#94]
![a](https://user-images.githubusercontent.com/8971893/36135693-b70cb2d6-10c7-11e8-84a9-e85b3db1bc73.png)

what's meaning of the `idname`?
And if I add new train data, what's idname should I use?

![b](https://user-images.githubusercontent.com/8971893/36135665-990292b0-10c7-11e8-8793-60dc3cd6486d.png)
what's meaning of the `ishard`?

**Comment by Cysu** [comment]
`idname` is the id of a person. You may specify new ids for your own training data. `ishard` was to mark whether a pedestrian is a hard sample (low resolution, bad lighting, etc.)
