### ISSUE TITLE
About initialization 

### ISSUE THREAD

**Issue by xuyan1115** [ShuangLI59/person_search#96]
Hi, 
The whole network can be divided into two parts: stem part and identification part, I think the resnet50 pretrained model is used to initialize stem part.

How do you initialize the identification part?

**Comment by animebing** [comment]
@xuyan1115 In the section **3.1 Model Structure** of the paper, it is said that **conv1 to conv4_3** of resnet-50 is used as the stem part and the rest **conv4_4 to conv5_3** is used as identification part, so the identification part still can be initialized by resnet-50

**Comment by Cysu** [comment]
@animebing thanks very much!
