### ISSUE TITLE
Normalization about lookup table?

### ISSUE THREAD

**Issue by animebing** [ShuangLI59/person_search#98]
In the paper, it is said that after **updating lookup table**, the vector should be normalized, but in `Backward_cpu` of `labeled_matching_layer.cpp`, I don't find the normalization step, can you tell me where to find the normalization step? thank you.

**Comment by Cysu** [comment]
We reuse the [Normalize layer](https://github.com/ShuangLI59/person_search/blob/master/models/psdb/resnet50/train.prototxt#L3071-L3076) in caffe for this purpose.
